import React from "react";
import {
  FiActivity,
  FiAirplay,
  FiAlertCircle,
  FiAlertOctagon,
  FiAlertTriangle,
  FiAlignCenter,
  FiAlignJustify,
  FiAlignLeft,
  FiAlignRight,
  FiAnchor,
  FiAperture,
  FiArchive,
  FiArrowDown,
  FiArrowDownCircle,
  FiArrowDownLeft,
  FiArrowDownRight,
  FiArrowLeft,
  FiArrowLeftCircle,
  FiArrowRight,
  FiArrowRightCircle,
  FiArrowUp,
  FiArrowUpCircle,
  FiArrowUpLeft,
  FiArrowUpRight,
  FiAtSign,
  FiAward,
  FiBarChart,
  FiBarChart2,
  FiBattery,
  FiBatteryCharging,
  FiBell,
  FiBellOff,
  FiBluetooth,
  FiBold,
  FiBook,
  FiBookOpen,
  FiBookmark,
  FiBox,
  FiBriefcase,
  FiCalendar,
  FiCamera,
  FiCameraOff,
  FiCast,
  FiCheck,
  FiCheckCircle,
  FiCheckSquare,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiChevronUp,
  FiChevronsDown,
  FiChevronsLeft,
  FiChevronsRight,
  FiChevronsUp,
  FiChrome,
  FiCircle,
  FiClock,
  FiCloud,
  FiCloudDrizzle,
  FiCloudLightning,
  FiCloudOff,
  FiCloudRain,
  FiCloudSnow,
  FiCode,
  FiCodepen,
  FiCodesandbox,
  FiCoffee,
  FiColumns,
  FiCommand,
  FiCompass,
  FiCopy,
  FiCornerDownLeft,
  FiCornerDownRight,
  FiCornerLeftDown,
  FiCornerLeftUp,
  FiCornerRightDown,
  FiCornerRightUp,
  FiCornerUpLeft,
  FiCornerUpRight,
  FiCpu,
  FiCreditCard,
  FiCrop,
  FiCrosshair,
  FiDatabase,
  FiDelete,
  FiDisc,
  FiDivide,
  FiDollarSign,
  FiDownload,
  FiDribbble,
  FiDroplet,
  FiEdit,
  FiEdit2,
  FiEdit3,
  FiExternalLink,
  FiEye,
  FiEyeOff,
  FiFacebook,
  FiFastForward,
  FiFeather,
  FiFilm,
  FiFilter,
  FiFlag,
  FiFolder,
  FiFolderPlus,
  FiGithub,
  FiGitlab,
  FiGlobe,
  FiGrid,
  FiHardDrive,
  FiHash,
  FiHeart,
  FiHelpCircle,
  FiHome,
  FiImage,
  FiInbox,
  FiInfo,
  FiInstagram,
  FiItalic,
  FiLayers,
  FiLayout,
  FiLink,
  FiLink2,
  FiLinkedin,
  FiList,
  FiLoader,
  FiLock,
  FiLogIn,
  FiLogOut,
  FiMail,
  FiMap,
  FiMapPin,
  FiMaximize,
  FiMaximize2,
  FiMenu,
  FiMessageCircle,
  FiMessageSquare,
  FiMic,
  FiMicOff,
  FiMinimize,
  FiMinimize2,
  FiMinus,
  FiMinusCircle,
  FiMinusSquare,
  FiMonitor,
  FiMoon,
  FiMoreHorizontal,
  FiMoreVertical,
  FiMove,
  FiMusic,
  FiNavigation,
  FiNavigation2,
  FiOctagon,
  FiPackage,
  FiPaperclip,
  FiPause,
  FiPauseCircle,
  FiPenTool,
  FiPercent,
  FiPhone,
  FiPhoneCall,
  FiPhoneForwarded,
  FiPhoneIncoming,
  FiPhoneMissed,
  FiPhoneOff,
  FiPhoneOutgoing,
  FiPieChart,
  FiPlay,
  FiPlayCircle,
  FiPlus,
  FiPlusCircle,
  FiPlusSquare,
  FiPocket,
  FiPower,
  FiPrinter,
  FiRadio,
  FiRefreshCcw,
  FiRefreshCw,
  FiRepeat,
  FiRewind,
  FiRotateCcw,
  FiRotateCw,
  FiRss,
  FiSave,
  FiScissors,
  FiSearch,
  FiSend,
  FiServer,
  FiSettings,
  FiShare,
  FiShare2,
  FiShield,
  FiShoppingBag,
  FiShoppingCart,
  FiShuffle,
  FiSidebar,
  FiSkipBack,
  FiSkipForward,
  FiSlack,
  FiSlash,
  FiSliders,
  FiSmartphone,
  FiSmile,
  FiSpeaker,
  FiSquare,
  FiStar,
  FiStopCircle,
  FiSun,
  FiSunrise,
  FiSunset,
  FiTablet,
  FiTag,
  FiTarget,
  FiTerminal,
  FiThermometer,
  FiThumbsDown,
  FiThumbsUp,
  FiToggleLeft,
  FiToggleRight,
  FiTool,
  FiTrash,
  FiTrash2,
  FiTrendingDown,
  FiTrendingUp,
  FiTriangle,
  FiTruck,
  FiTv,
  FiTwitch,
  FiTwitter,
  FiType,
  FiUmbrella,
  FiUnderline,
  FiUnlock,
  FiUpload,
  FiUser,
  FiUserCheck,
  FiUserMinus,
  FiUserPlus,
  FiUserX,
  FiUsers,
  FiVideo,
  FiVideoOff,
  FiVoicemail,
  FiVolume,
  FiVolume1,
  FiVolume2,
  FiVolumeX,
  FiWatch,
  FiWifi,
  FiWifiOff,
  FiWind,
  FiX,
  FiXCircle,
  FiXOctagon,
  FiXSquare,
  FiYoutube,
  FiZap,
  FiZapOff,
  FiZoomIn,
  FiZoomOut,
} from "react-icons/fi";

// We'll use LucideIcons for any icon not available in Feather icons
import {
  LuCode,
  LuPaintbrush,
  LuSmartphone,
  LuServer,
  LuShieldCheck,
  LuCloud,
  LuBrain,
  LuCog,
  LuMegaphone,
  LuShoppingCart,
  LuLaptop,
  LuUsers,
  LuSearch,
  LuFileText,
  LuDatabase,
  LuCamera,
  LuMail,
} from "react-icons/lu";
import { FaUserShield } from "react-icons/fa6";
import {
  FaKey,
  FaCheckCircle,
  FaSyncAlt,
  FaRegAddressCard,
} from "react-icons/fa";
// import { BsPassport } from "react-icons/bs";

import { CiLock, CiPassport1, CiImageOn } from "react-icons/ci";

import { HiLightBulb, HiCubeTransparent, HiUserGroup } from "react-icons/hi2";
import { HiRefresh, HiShieldCheck, HiHeart } from "react-icons/hi";

// ri icon
import { RiRobot2Line } from "react-icons/ri";

import { AiOutlineRobot } from "react-icons/ai";

import { MdOutlineModelTraining } from "react-icons/md";

import { GrDocumentPdf } from "react-icons/gr";

export interface IconRendererProps {
  iconName: string;
  className?: string;
  size?: number | string;
  color?: string;
  strokeWidth?: number;
}

type IconComponentType = React.ComponentType<{
  className?: string;
  strokeWidth?: number;
}>;

const IconRenderer: React.FC<IconRendererProps> = ({
  iconName,
  className = "h-5 w-5",
  size,
  color = "currentColor",
  strokeWidth = 2,
}) => {
  // Compute combined className
  const combinedClassName = size
    ? `${className} h-${size} w-${size} ${color}`
    : `${className} ${color}`;

  // Map of icon name to icon component (not JSX.Element)
  const iconMap: { [key: string]: IconComponentType } = {
    // Feather Icons (already outline)
    FiCode: FiCode,
    FiPenTool: FiPenTool,
    FiTrendingUp: FiTrendingUp,
    FiSmartphone: FiSmartphone,
    FiServer: FiServer,
    FiShield: FiShield,
    FiCloud: FiCloud,
    FiCpu: FiCpu,
    FiActivity: FiActivity,
    FiAirplay: FiAirplay,
    FiAlertCircle: FiAlertCircle,
    FiAlertOctagon: FiAlertOctagon,
    FiAlertTriangle: FiAlertTriangle,
    FiAlignCenter: FiAlignCenter,
    FiAlignJustify: FiAlignJustify,
    FiAlignLeft: FiAlignLeft,
    FiAlignRight: FiAlignRight,
    FiAnchor: FiAnchor,
    FiAperture: FiAperture,
    FiArchive: FiArchive,
    FiArrowDown: FiArrowDown,
    FiArrowLeft: FiArrowLeft,
    FiArrowRight: FiArrowRight,
    FiArrowUp: FiArrowUp,
    FiAtSign: FiAtSign,
    FiAward: FiAward,
    FiBarChart: FiBarChart,
    FiBarChart2: FiBarChart2,
    FiBattery: FiBattery,
    FiBell: FiBell,
    FiBellOff: FiBellOff,
    FiBook: FiBook,
    FiBookmark: FiBookmark,
    FiBox: FiBox,
    FiBriefcase: FiBriefcase,
    FiCalendar: FiCalendar,
    FiCamera: FiCamera,
    FiClock: FiClock,
    FiDownload: FiDownload,
    FiEdit: FiEdit,
    FiEye: FiEye,
    FiGlobe: FiGlobe,
    FiGrid: FiGrid,
    FiHeart: FiHeart,
    FiHome: FiHome,
    FiImage: FiImage,
    FiInbox: FiInbox,
    FiLayers: FiLayers,
    FiLink: FiLink,
    FiList: FiList,
    FiLock: FiLock,
    FiMap: FiMap,
    FiMessageCircle: FiMessageCircle,
    FiMonitor: FiMonitor,
    FiMusic: FiMusic,
    FiPackage: FiPackage,
    FiPhone: FiPhone,
    FiPieChart: FiPieChart,
    FiPlay: FiPlay,
    FiPlus: FiPlus,
    FiRefreshCw: FiRefreshCw,
    FiSearch: FiSearch,
    FiSend: FiSend,
    FiSettings: FiSettings,
    FiShoppingBag: FiShoppingBag,
    FiShoppingCart: FiShoppingCart,
    FiStar: FiStar,
    FiTag: FiTag,
    FiTool: FiTool,
    FiTrash: FiTrash,
    FiUser: FiUser,
    FiUsers: FiUsers,
    FiVideo: FiVideo,
    FiWifi: FiWifi,
    FiZap: FiZap,
    FiHardDrive: FiHardDrive,
    FiExternalLink: FiExternalLink,

    // Lucide Icons (outline alternative for Font Awesome)
    FaCode: LuCode,
    FaPaintBrush: LuPaintbrush,
    FaMobileAlt: LuSmartphone,
    FaServer: LuServer,
    FaShield: LuShieldCheck,
    FaCloud: LuCloud,
    FaRobot: LuBrain,
    FaCog: LuCog,
    FaBullhorn: LuMegaphone,
    FaShoppingCart: LuShoppingCart,
    FaLaptopCode: LuLaptop,
    FaUserFriends: LuUsers,
    FaSearch: LuSearch,
    FaFileAlt: LuFileText,
    FaDatabase: LuDatabase,
    FaPhotoVideo: LuCamera,
    FaEnvelope: LuMail,
    FaUserShield: FaUserShield,
    "FaCheckCircle ": FaCheckCircle,
    FiPaperclip: FiPaperclip,
    FaSyncAlt: FaSyncAlt,

    // Ri Icon
    RiRobot2Line: RiRobot2Line,
    AiOutlineRobot: AiOutlineRobot,
    FaKey: FaKey,

    HiLightBulb: HiLightBulb,
    HiCubeTransparent: HiCubeTransparent,
    HiUserGroup: HiUserGroup,
    HiRefresh: HiRefresh,
    HiShieldCheck: HiShieldCheck,
    HiHeart: HiHeart,
    CiLock: CiLock,

    FineTuning: MdOutlineModelTraining,
    PDF: GrDocumentPdf,
    NID: FaRegAddressCard,
    Passport: CiPassport1,
    Image: CiImageOn,

    // Add more icons as needed
  };

  // Render the icon component if it exists
  const IconComponent = iconMap[iconName];

  if (IconComponent) {
    return (
      <IconComponent className={combinedClassName} strokeWidth={strokeWidth} />
    );
  }

  // Fallback icon
  return (
    <FiHelpCircle className={combinedClassName} strokeWidth={strokeWidth} />
  );
};

export default IconRenderer;
